"""add feedback.value for manual topic weights

Revision ID: 2813f1a15b8e
Revises: 9ef644e53753
Create Date: 2026-07-30 09:46:02.109700
"""

from alembic import op
import sqlalchemy as sa


revision = "2813f1a15b8e"
down_revision = "9ef644e53753"
branch_labels = None
depends_on = None

# ---------------------------------------------------------------------------
# READ THIS FILE BEFORE APPLYING IT.
#
# If it came from `--autogenerate` it is a DRAFT, and drafts have known blind
# spots:
#   * A column rename is emitted as drop_column + add_column. Applying that
#     deletes every value in the column. The fix is one line:
#     op.alter_column("<table>", "<old>", new_column_name="<new>")
#   * A type change becomes a cast that runs against existing rows and may
#     truncate or fail.
#   * Data does not migrate itself -- backfills have to be written by hand.
#
# `upgrade` refuses to run while the marker below is present. Delete that line
# by hand once you have read and corrected this migration. Nothing in the
# tooling removes it for you; that deletion is the approval.
# ---------------------------------------------------------------------------
#
# Reviewed and approved (marker removed).
#
# Written by hand (`new --empty`), so there is no autogenerated diff to audit --
# but the same three blind spots are worth answering explicitly:
#
# * No rename. `value` is a genuinely new column on `feedback`; nothing is
#   dropped, so no data is at risk and there is no drop+add pair to collapse.
# * No type change. Nothing existing is cast.
# * No backfill is needed, and NULL is the correct value for every existing row.
#   `value` only means anything for kind='set_topic', which no row can be yet
#   (the kind ships in this same change), and `recommend.profile.replay` ignores
#   a set_topic whose value is NULL rather than reading it as 0 -- so even a
#   hand-inserted malformed row cannot silently zero a topic weight.
#
# Nullable rather than NOT NULL DEFAULT 0 for exactly that reason: 0 is a
# meaningful weight ("forget this topic"), so it must not double as "no value
# recorded". Matches how posts.affinity_score is declared.
# ---------------------------------------------------------------------------


def upgrade() -> None:
    op.add_column("feedback", sa.Column("value", sa.Float(), nullable=True))


def downgrade() -> None:
    op.drop_column("feedback", "value")
