"""add posts.banner_url

Revision ID: 2c4a5f0070bf
Revises: cac5689addb7
Create Date: 2026-07-22 12:53:42.679469
"""

from alembic import op
import sqlalchemy as sa


revision = "2c4a5f0070bf"
down_revision = "cac5689addb7"
branch_labels = None
depends_on = None

# ---------------------------------------------------------------------------
# READ THIS FILE BEFORE APPLYING IT.
#
# If it came from `--autogenerate` it is a DRAFT, and drafts have known blind
# spots:
#   * A column rename is emitted as drop_column + add_column. Applying that
#     deletes every value in the column. The fix is one line:
#     op.alter_column("<table>", "<old>", new_column_name="<new>")
#   * A type change becomes a cast that runs against existing rows and may
#     truncate or fail.
#   * Data does not migrate itself -- backfills have to be written by hand.
#
# `upgrade` refuses to run while the marker below is present. Delete that line
# by hand once you have read and corrected this migration. Nothing in the
# tooling removes it for you; that deletion is the approval.
# ---------------------------------------------------------------------------
#
# Reviewed and approved (marker removed).
#
# Reviewed: nullable add_column (no rename, no type change, no NOT NULL). Followed
# by a hand-written data backfill — the autogenerate diff can't see it — that
# denormalizes the feed banner onto existing FEATURE posts (aggregates render from
# their items and don't use the column). Mirrors pipeline.story_banner_url /
# templating._story_banner: the first image among the story's items, ordered by
# item id then media_refs position, so it matches what the feed showed before.

# Per story, the first image ref (item id, then array position) across its items.
_BACKFILL = """
UPDATE posts p
SET banner_url = sub.url
FROM (
    SELECT DISTINCT ON (si.story_id) si.story_id, ref.value->>'url' AS url
    FROM source_items si
    CROSS JOIN LATERAL
        jsonb_array_elements(COALESCE(si.media_refs, '[]'::jsonb))
        WITH ORDINALITY AS ref(value, ord)
    WHERE ref.value->>'kind' = 'image'
      AND COALESCE(ref.value->>'url', '') <> ''
    ORDER BY si.story_id, si.id, ref.ord
) sub
WHERE p.story_id = sub.story_id AND p.kind = 'feature';
"""


def upgrade() -> None:
    op.add_column("posts", sa.Column("banner_url", sa.Text(), nullable=True))
    op.execute(_BACKFILL)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "banner_url")
    # ### end Alembic commands ###
