"""chat messages and story origin

Revision ID: 60e3a70e4e58
Revises: bed89c48b376
Create Date: 2026-08-11 19:38:53.991131
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '60e3a70e4e58'
down_revision = 'bed89c48b376'
branch_labels = None
depends_on = None

# Reviewed 2026-08-11. Autogenerated draft, read in full and corrected once:
#
#   * No renames. `chat_messages` is a new table and `stories.origin` is a new
#     column, not a rename -- the diff carries no drop_column against `stories`.
#   * No type changes, so nothing casts against existing rows.
#   * The one thing autogenerate could not see: `stories` is populated, and
#     Postgres cannot add a NOT NULL column to a populated table without a
#     default. The generated `add_column(..., nullable=False)` would have failed
#     outright. Corrected to add WITH server_default='ingest' (which is also the
#     backfill for every existing story: none of them were user-requested), then
#     drop the default so the ORM owns it -- the convention 3daf6dbaefc3
#     established for this schema.
#
# `chat_messages.tool_args` is NOT NULL with no server_default, matching the
# other JSONB columns: the table is new and empty, so there is nothing to
# backfill, and every insert goes through the ORM's `default=dict`.


def upgrade() -> None:
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("post_id", sa.Integer(), nullable=True),
        sa.Column("tool_name", sa.String(length=50), nullable=True),
        sa.Column("tool_args", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tool_call_id", sa.String(length=64), nullable=True),
        sa.Column("proposal_status", sa.String(length=20), nullable=True),
        sa.Column("chain_id", sa.String(length=36), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_chat_messages_session", "chat_messages", ["session_id", "id"], unique=False
    )
    op.add_column(
        "stories",
        sa.Column("origin", sa.String(length=20), nullable=False, server_default="ingest"),
    )
    op.alter_column(
        "stories", "origin", server_default=None,
        existing_type=sa.String(length=20), existing_nullable=False,
    )


def downgrade() -> None:
    op.drop_column("stories", "origin")
    op.drop_index("ix_chat_messages_session", table_name="chat_messages")
    op.drop_table("chat_messages")
