"""baseline schema

The schema as it stood when the project moved from bootstrap.py's hand-written
DDL lists to Alembic (2026-07-20). It is the end state of everything those lists
did -- the articles->posts rename, every ADDITIVE_MIGRATIONS column, the 768->1024
vector widening, posts.title/summary/difficulty going nullable for aggregate
cards -- collapsed into one create-from-nothing revision.

Two consequences worth knowing:

* A database that predates Alembic already has all of this. It is adopted by
  stamping this revision rather than running it (bootstrap.py does that
  automatically, once, when it finds tables but no alembic_version).
* Procrastinate's tables are deliberately absent: that schema is owned by
  procrastinate's own tool, which bootstrap applies separately, and env.py
  excludes those tables from autogenerate so they are never diffed.

Revision ID: 794b362d6e01
Revises:
Create Date: 2026-07-20 13:20:30.724317
"""

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

revision = '794b362d6e01'
down_revision = None
branch_labels = None
depends_on = None

# Reviewed 2026-07-20: checked table by table against models.py, and the missing
# CREATE EXTENSION added below. The UNREVIEWED marker was deleted by hand at that
# point -- that deletion is what lets `upgrade` run.


def upgrade() -> None:
    # HAND-ADDED, not autogenerated: the Vector columns below cannot be created
    # without this, and a schema diff has no way to know an extension is needed.
    # Exactly the class of thing --autogenerate cannot see.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_state',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('llm_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=True),
    sa.Column('story_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('attempt_id', sa.String(length=36), nullable=True),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('chain_id', sa.String(length=36), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('request', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_calls_post_id'), 'llm_calls', ['post_id'], unique=False)
    op.create_index(op.f('ix_llm_calls_story_id'), 'llm_calls', ['story_id'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('credibility_rating', sa.Float(), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('http_etag', sa.Text(), nullable=True),
    sa.Column('http_last_modified', sa.Text(), nullable=True),
    sa.Column('cooldown_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('triage_decision', sa.String(length=20), nullable=True),
    sa.Column('triage_reason', sa.Text(), nullable=True),
    sa.Column('rank_score', sa.Float(), nullable=True),
    sa.Column('research_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('centroid', Vector(1024), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('first_item_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_item_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sections', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reading_time_minutes', sa.Integer(), nullable=False),
    sa.Column('model_used', sa.Text(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('media_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding', Vector(1024), nullable=True),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('arxiv_id', sa.String(length=50), nullable=True),
    sa.Column('fetch_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    op.create_index('ix_source_items_published_at', 'source_items', ['published_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_source_items_published_at', table_name='source_items')
    op.drop_table('source_items')
    op.drop_table('posts')
    op.drop_table('stories')
    op.drop_table('sources')
    op.drop_table('pipeline_runs')
    op.drop_index(op.f('ix_llm_calls_story_id'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_post_id'), table_name='llm_calls')
    op.drop_table('llm_calls')
    op.drop_table('app_state')
    # ### end Alembic commands ###
