"""add recommendation schema

Revision ID: 9ef644e53753
Revises: 2c4a5f0070bf
Create Date: 2026-07-29 21:10:31.970074
"""

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

revision = '9ef644e53753'
down_revision = '2c4a5f0070bf'
branch_labels = None
depends_on = None

# ---------------------------------------------------------------------------
# READ THIS FILE BEFORE APPLYING IT.
#
# If it came from `--autogenerate` it is a DRAFT, and drafts have known blind
# spots:
#   * A column rename is emitted as drop_column + add_column. Applying that
#     deletes every value in the column. The fix is one line:
#     op.alter_column("<table>", "<old>", new_column_name="<new>")
#   * A type change becomes a cast that runs against existing rows and may
#     truncate or fail.
#   * Data does not migrate itself -- backfills have to be written by hand.
#
# `upgrade` refuses to run while the marker below is present. Delete that line
# by hand once you have read and corrected this migration. Nothing in the
# tooling removes it for you; that deletion is the approval.
# ---------------------------------------------------------------------------
#
# Reviewed and approved (marker removed).
#
# The whole Phase 4 schema in one revision: it was drafted as three (topics /
# feedback+profile / posts columns) but never applied to any database and never
# committed, so there was no history to preserve by keeping them apart. One
# revision means one pre-migration pg_dump and one all-or-nothing transaction —
# no state where the vocabulary exists but the feedback log does not.
#
# Reviewed against models.Topic / models.Feedback / models.InterestProfile /
# models.Post, column for column. Two effects only: three CREATE TABLEs, and
# three NULLABLE columns added to `posts`. No drop+add pair anywhere, so no
# rename to rescue; no type change, so no cast runs against existing rows; no
# NOT NULL on an existing table, so no backfill is needed to make current rows
# legal. CREATE EXTENSION vector is already in place from the baseline, and
# every Vector(1024) matches models.EMBEDDING_DIM.
#
# What the diff cannot see, table by table:
#
# topics — `aliases` is NOT NULL without a server_default, matching how
#   stories.topics / posts.topics are declared in the baseline: every insert goes
#   through the ORM, which supplies the `default=list`. No indexes beyond the
#   unique slug: alias containment and the cosine nearest-neighbour scan both run
#   over tens to a few hundred rows, where GIN or ivfflat costs more than it
#   saves. The vocabulary is deliberately NOT derived here — clustering the
#   existing free-text tags needs the embedding model and a naming pass, and the
#   result is reviewed before it is applied (the two-phase propose/apply
#   bootstrap in recommend/topics.py).
#
# feedback — `post_id` is ON DELETE SET NULL, not CASCADE. The retention prune
#   deletes archived posts, and a feedback event must survive that: the profile
#   is REPLAYED from this log, so dropping an event would silently rewrite the
#   reader's interests as a side effect of a retention sweep. Replay never reads
#   post_id; the event carries its own embedding and topic snapshot precisely so
#   the log is self-sufficient. The created_at index serves replay (whole log in
#   timestamp order), the post_id index the feed's one-query button-state lookup.
#
# interest_profile — needs no seed row: recommend.profile.load() reads an absent
#   row as an empty profile (cold start ranks on pure freshness), and rebuild()
#   creates it on the first replay.
#
# posts.affinity_score / score_components / scored_at — no backfill is required
#   to make these CORRECT either, which is the part worth stating: NULL
#   affinity_score is read as neutral (0) by the feed's ranking expression, so
#   until the score stage first runs every existing post ranks on freshness
#   alone — exactly the ordering the feed had before this migration. Scoring the
#   corpus needs the interest profile, which is data the reader has to supply, so
#   it belongs to a job (POST /api/jobs/defer/score) and not here.
# ---------------------------------------------------------------------------


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interest_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('liked_centroid', Vector(1024), nullable=True),
    sa.Column('disliked_centroid', Vector(1024), nullable=True),
    sa.Column('topic_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('difficulty_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('blocked_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('blocked_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('intent_statement', sa.Text(), nullable=True),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('rebuilt_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(1024), nullable=True),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('topic', sa.Text(), nullable=True),
    sa.Column('source_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding', Vector(1024), nullable=True),
    sa.Column('topics_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('nl_text', sa.Text(), nullable=True),
    sa.Column('parsed_intent', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feedback_created_at', 'feedback', ['created_at'], unique=False)
    op.create_index(op.f('ix_feedback_post_id'), 'feedback', ['post_id'], unique=False)
    op.add_column('posts', sa.Column('affinity_score', sa.Float(), nullable=True))
    op.add_column('posts', sa.Column('score_components', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('posts', sa.Column('scored_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'scored_at')
    op.drop_column('posts', 'score_components')
    op.drop_column('posts', 'affinity_score')
    op.drop_index(op.f('ix_feedback_post_id'), table_name='feedback')
    op.drop_index('ix_feedback_created_at', table_name='feedback')
    op.drop_table('feedback')
    op.drop_table('topics')
    op.drop_table('interest_profile')
    # ### end Alembic commands ###
