"""matsedel weeks and dishes

Matsedel's own tables (0046). A plugin may define tables and they go in core's
single Alembic history, because every plugin currently imaginable ships in this
repository; `migrations/env.py` imports `episteme.correspondents` so autogenerate
can see them at all.

Reviewed 2026-08-28, whole file read. Two new tables and nothing else: no
drop_column anywhere, so no rename is hiding here, no type change, and no
backfill, because neither table has a row yet and nothing derives from them. The
constraints match `correspondents/matsedel/models.py`: the week is unique per
(source, week_key) so a re-read corrects a week in place, a line is unique per
(week, position), and both cascade from their parent so deleting a `sources` row
does not leave a menu behind. No index on `matsedel_weeks.monday`, deliberately:
four rows a week is roughly 200 a year, and a sequential scan of that is free.

Revision ID: bbe93808d5dc
Revises: edd1895c150c
Create Date: 2026-08-28 23:24:51.194256
"""

from alembic import op
import sqlalchemy as sa


revision = "bbe93808d5dc"
down_revision = "edd1895c150c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "matsedel_weeks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("week_key", sa.String(length=10), nullable=False),
        sa.Column("monday", sa.Date(), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "week_key", name="uq_matsedel_weeks_source_week"),
    )
    op.create_table(
        "matsedel_dishes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("week_id", sa.Integer(), nullable=False),
        sa.Column("serve_date", sa.Date(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["week_id"], ["matsedel_weeks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("week_id", "position", name="uq_matsedel_dishes_week_position"),
    )
    op.create_index(
        "ix_matsedel_dishes_serve_date", "matsedel_dishes", ["serve_date"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_matsedel_dishes_serve_date", table_name="matsedel_dishes")
    op.drop_table("matsedel_dishes")
    op.drop_table("matsedel_weeks")
    # ### end Alembic commands ###
