"""add voices catalog and audio provenance

Revision ID: cac5689addb7
Revises: 9f854ae4067e
Create Date: 2026-07-21 15:03:41.616159
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "cac5689addb7"
down_revision = "9f854ae4067e"
branch_labels = None
depends_on = None

# Reviewed 2026-07-21: purely additive — a new (empty) `voices` catalog table and
# two nullable columns on `post_audio` (provider/params provenance). No renames,
# no type changes, no backfill: existing post_audio rows take NULL provider/params
# and their old `mp3` format falls through the opus cache check to re-narrate on
# demand. New voices are seeded via the ORM (seeds.seed_voices), so the NOT NULL
# columns without server defaults match the codebase's `sources` pattern.


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "voices",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("provider_voice_id", sa.Text(), nullable=True),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("post_audio", sa.Column("provider", sa.Text(), nullable=True))
    op.add_column(
        "post_audio", sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("post_audio", "params")
    op.drop_column("post_audio", "provider")
    op.drop_table("voices")
    # ### end Alembic commands ###
