"""posts expires_at

The mirror of `publish_at` (0046 + TODO.md:25): when a post stops being visible
in the feed, NULL = never. Today's lunch menu is worth reading until the kitchen
closes and is purely historical after. Feed only; the post keeps its own URL.

Reviewed 2026-08-28, whole file read. One nullable column added, no drop_column
beside it so no rename is hiding here, no type change, and nothing to backfill:
NULL is exactly right for every post that already exists, none of which expires.

Revision ID: edd1895c150c
Revises: 1e872520d227
Create Date: 2026-08-28 23:00:17.948466
"""

from alembic import op
import sqlalchemy as sa


revision = "edd1895c150c"
down_revision = "1e872520d227"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "expires_at")
    # ### end Alembic commands ###
