"""The review gate and the pre-migration backup are the two things standing
between an autogenerated draft and the production database, so they get tested
like load-bearing code: that the gate catches the data-loss patterns, that it
does not cry wolf on safe ones, that the shipped revisions are all approved, and
that the backup refuses to let a migration through when it cannot protect it."""

from pathlib import Path

import pytest

from episteme.migrations import MIGRATIONS_DIR, alembic_config, prebackup
from episteme.migrations.guard import (
    MARKER_LINE,
    analyze,
    annotate,
    is_unreviewed,
    verify,
    version_scripts,
)

HEADER = """\
from alembic import op
import sqlalchemy as sa

revision = 'abc123'
down_revision = None
"""


def write_migration(tmp_path: Path, upgrade: str, downgrade: str = "pass", marker: bool = True):
    """Build a migration file the way the template does, returning its path."""
    versions = tmp_path / "versions"
    versions.mkdir(exist_ok=True)
    body = HEADER
    if marker:
        body += f"\n{MARKER_LINE}\n"
    body += f"\n\ndef upgrade() -> None:\n    {upgrade}\n\n\ndef downgrade() -> None:\n    {downgrade}\n"
    path = versions / "abc123_test.py"
    path.write_text(body, encoding="utf-8")
    return path


def codes(path: Path) -> set[str]:
    return {f.code for f in analyze(path)}


# --- the marker ----------------------------------------------------------


def test_marker_blocks_until_deleted(tmp_path):
    path = write_migration(tmp_path, "pass")
    assert is_unreviewed(path)
    assert verify(tmp_path), "an unreviewed revision must block the upgrade"

    # Approval is exactly this: the line goes away.
    path.write_text(
        path.read_text(encoding="utf-8").replace(f"{MARKER_LINE}\n", ""), encoding="utf-8"
    )
    assert not is_unreviewed(path)
    assert verify(tmp_path) == []


def test_marker_is_parsed_not_grepped(tmp_path):
    """Mentioning the marker in prose must not count -- guard.py's own docstring
    contains the string, and a migration explaining why it was approved should
    be able to say the word without re-blocking itself."""
    path = write_migration(tmp_path, "pass", marker=False)
    path.write_text(
        f'"""Approved: the {MARKER_LINE} line was deleted."""\n'
        f"# see also: {MARKER_LINE}\n" + path.read_text(encoding="utf-8"),
        encoding="utf-8",
    )
    assert not is_unreviewed(path)


def test_marker_set_to_false_does_not_block(tmp_path):
    path = write_migration(tmp_path, "pass", marker=False)
    path.write_text(path.read_text(encoding="utf-8") + "\nUNREVIEWED = False\n", encoding="utf-8")
    assert not is_unreviewed(path)


# --- hazard analysis -----------------------------------------------------


@pytest.mark.parametrize(
    "statement,expected",
    [
        ("op.drop_table('posts')", "drop_table"),
        ("op.drop_column('posts', 'summary')", "drop_column"),
        ("op.alter_column('posts', 'kind', type_=sa.Text())", "type_change"),
        ("op.execute('DELETE FROM posts')", "raw_sql"),
        ("op.execute('TRUNCATE llm_calls')", "raw_sql"),
    ],
)
def test_destructive_operations_are_flagged(tmp_path, statement, expected):
    path = write_migration(tmp_path, statement)
    findings = analyze(path)
    assert expected in {f.code for f in findings}
    assert any(f.severe for f in findings)


@pytest.mark.parametrize(
    "statement",
    [
        "op.add_column('posts', sa.Column('x', sa.Text()))",
        "op.create_index('ix_x', 'posts', ['x'])",
        "op.alter_column('posts', 'old', new_column_name='new')",
        "op.execute('CREATE EXTENSION IF NOT EXISTS vector')",
        "op.alter_column('posts', 'kind', server_default=None)",
    ],
)
def test_safe_operations_are_not_flagged_severe(tmp_path, statement):
    """Crying wolf is a real failure mode: if routine migrations light up red,
    the DANGER lines stop being read."""
    path = write_migration(tmp_path, statement)
    assert not any(f.severe for f in analyze(path))


def test_rename_split_into_drop_and_add_is_called_out(tmp_path):
    """The exact shape autogenerate produces for a rename, and the exact reason
    this gate exists."""
    path = write_migration(
        tmp_path,
        "op.drop_column('posts', 'summary')\n"
        "    op.add_column('posts', sa.Column('abstract', sa.Text()))",
    )
    findings = analyze(path)
    assert "possible_rename" in {f.code for f in findings}
    assert any("data will be lost" in f.message for f in findings)


def test_drop_and_add_on_different_tables_is_not_a_rename(tmp_path):
    path = write_migration(
        tmp_path,
        "op.drop_column('posts', 'summary')\n"
        "    op.add_column('stories', sa.Column('abstract', sa.Text()))",
    )
    assert "possible_rename" not in codes(path)


def test_downgrade_is_not_analyzed(tmp_path):
    """Every migration's downgrade drops things; flagging them would fire on all
    of them and train the reader to skip the warnings."""
    path = write_migration(tmp_path, "pass", downgrade="op.drop_table('posts')")
    assert analyze(path) == []


def test_missing_upgrade_is_itself_a_finding(tmp_path):
    versions = tmp_path / "versions"
    versions.mkdir()
    path = versions / "abc123_test.py"
    path.write_text(HEADER, encoding="utf-8")
    assert "no_upgrade" in codes(path)


# --- annotation ----------------------------------------------------------


def test_hazards_are_written_above_the_marker(tmp_path):
    """The warning has to sit between the reader and the line they came to
    delete, or the deletion becomes a reflex."""
    path = write_migration(tmp_path, "op.drop_column('posts', 'summary')")
    annotate(path)
    lines = path.read_text(encoding="utf-8").splitlines()
    marker_at = lines.index(MARKER_LINE)
    warning_at = next(i for i, line in enumerate(lines) if "drops a column" in line)
    assert warning_at < marker_at
    assert is_unreviewed(path), "annotating must not approve anything"


def test_annotate_is_idempotent(tmp_path):
    path = write_migration(tmp_path, "op.drop_column('posts', 'summary')")
    annotate(path)
    once = path.read_text(encoding="utf-8")
    annotate(path)
    assert path.read_text(encoding="utf-8") == once


# --- the revisions actually shipped --------------------------------------


def test_shipped_revisions_are_reviewed():
    assert verify(MIGRATIONS_DIR) == [], "a revision in the repo still needs review"


def test_shipped_revisions_form_one_chain():
    """Two heads mean `upgrade head` is ambiguous and the stack fails to boot."""
    from alembic.script import ScriptDirectory

    config = alembic_config()
    config.attributes["applies_no_ddl"] = True
    assert len(ScriptDirectory.from_config(config).get_heads()) == 1


def test_every_revision_is_importable_and_has_both_directions():
    for script in version_scripts(MIGRATIONS_DIR):
        source = script.read_text(encoding="utf-8")
        assert "def upgrade()" in source and "def downgrade()" in source, script.name


# --- the pre-migration backup --------------------------------------------
#
# The dump is fail-closed, so every test here is really asking one of two
# questions: does it refuse when it cannot protect the data, and does it stay
# out of the way when there is nothing to protect? A false "nothing to protect"
# is the expensive direction — it migrates real rows with no dump — so the
# unknown cases below are all asserted to take the backup.


class FakeResult:
    def __init__(self, value):
        self._value = value

    def scalar(self):
        return self._value


class FakeConnection:
    """Answers the three probes prebackup makes, by SQL substring."""

    def __init__(self, *, has_tables=True, has_version_table=True, revision="abc123"):
        self.has_tables = has_tables
        self.has_version_table = has_version_table
        self.revision = revision

    async def execute(self, statement):
        sql = str(statement)
        if "to_regclass('sources')" in sql:
            return FakeResult("sources" if self.has_tables else None)
        if "to_regclass('alembic_version')" in sql:
            return FakeResult("alembic_version" if self.has_version_table else None)
        if "version_num" in sql:
            return FakeResult(self.revision)
        raise AssertionError(f"unexpected query: {sql}")


@pytest.fixture
def dumps(monkeypatch):
    """Record every dump taken, with pg_dump present and backups enabled."""
    from episteme.config import settings
    from episteme.worker import backup as backup_module

    taken = []

    async def fake_run_backup():
        taken.append(True)
        return Path("/backups/episteme-test.dump")

    monkeypatch.setattr(backup_module, "run_backup", fake_run_backup)
    monkeypatch.setattr(prebackup.shutil, "which", lambda _: "/usr/bin/pg_dump")
    monkeypatch.setattr(settings, "backup_enabled", True)
    return taken


async def test_a_fresh_database_is_not_dumped(dumps):
    """No application tables means nothing exists yet that a migration could eat."""
    await prebackup.backup_before_migrating(
        FakeConnection(has_tables=False, has_version_table=False), target="head_rev"
    )
    assert dumps == []


async def test_a_database_already_at_the_target_is_not_dumped(dumps):
    """Otherwise every `docker compose up` pays for a full pg_dump to apply
    nothing — which is how a safety measure gets switched off."""
    await prebackup.backup_before_migrating(FakeConnection(revision="abc123"), target="abc123")
    assert dumps == []


async def test_a_pending_revision_is_dumped(dumps):
    await prebackup.backup_before_migrating(FakeConnection(revision="abc123"), target="def456")
    assert dumps == [True]


async def test_an_unresolvable_target_is_dumped(dumps):
    """`target=None` is "alembic could not tell us where this is going" — a
    relative +1, a downgrade. The unknown case must fall on the side of taking a
    backup, never on the side of skipping one."""
    await prebackup.backup_before_migrating(FakeConnection(), target=None)
    assert dumps == [True]


async def test_a_pre_alembic_database_is_dumped(dumps):
    """Tables but no alembic_version: the adoption case, and the one database in
    the project's history with the most to lose."""
    await prebackup.backup_before_migrating(
        FakeConnection(has_version_table=False), target="baseline"
    )
    assert dumps == [True]


async def test_a_missing_pg_dump_blocks_the_migration(dumps, monkeypatch):
    """The host has no pg_dump and `backup_dir` is a container path, so this is
    what a host-side `upgrade` hits. It must refuse and say where to run it —
    migrating unprotected because the safety net lives elsewhere is the exact
    failure this whole module exists to close."""
    monkeypatch.setattr(prebackup.shutil, "which", lambda _: None)

    with pytest.raises(SystemExit) as excinfo:
        await prebackup.backup_before_migrating(FakeConnection(), target="def456")

    assert "docker compose run --rm migrate" in str(excinfo.value)
    assert dumps == []


async def test_a_failed_dump_blocks_the_migration(dumps, monkeypatch):
    """Fail-closed: a backup that could not be written is the situation this
    exists for, so it stops the migration rather than reporting a warning."""
    from episteme.worker import backup as backup_module

    async def exploding_backup():
        raise RuntimeError("pg_dump failed (exit 1): no space left on device")

    monkeypatch.setattr(backup_module, "run_backup", exploding_backup)

    with pytest.raises(SystemExit) as excinfo:
        await prebackup.backup_before_migrating(FakeConnection(), target="def456")

    assert "no space left on device" in str(excinfo.value)


async def test_backups_can_be_disabled_deliberately(dumps, monkeypatch):
    from episteme.config import settings

    monkeypatch.setattr(settings, "backup_enabled", False)
    await prebackup.backup_before_migrating(FakeConnection(), target="def456")
    assert dumps == []


def test_env_backs_up_before_running_migrations():
    """env.py cannot be imported (it runs migrations at module scope), so this
    reads it instead. Worth the awkwardness: env.py is the ONLY place the backup
    is wired in — that is the point of moving it there — so deleting the call is
    a silent, total loss of the protection with every test above still green."""
    import ast

    tree = ast.parse((MIGRATIONS_DIR / "env.py").read_text(encoding="utf-8"))
    runner = next(
        node
        for node in ast.walk(tree)
        if isinstance(node, ast.AsyncFunctionDef) and node.name == "run_async_migrations"
    )
    called = {
        node.func.id
        for node in ast.walk(runner)
        if isinstance(node, ast.Call) and isinstance(node.func, ast.Name)
    }
    assert "backup_before_migrating" in called
    assert "applies_ddl" in called, "the backup must share the review gate's trigger"


def test_bootstrap_has_no_second_backup_implementation():
    """Moved, not copied. Two implementations of "dump before DDL" is the shape
    that drifts until one of them quietly stops running — and the one that would
    stop running is whichever the operator is not looking at."""
    source = (Path(__file__).resolve().parents[1] / "src/episteme/bootstrap.py").read_text(
        encoding="utf-8"
    )
    assert "run_backup" not in source
