"""The review gate is the thing standing between an autogenerated draft and the
production database, so it gets tested like load-bearing code: that it catches
the data-loss patterns, that it does not cry wolf on safe ones, and that the
shipped revisions are all approved."""

from pathlib import Path

import pytest

from episteme.migrations import MIGRATIONS_DIR, alembic_config
from episteme.migrations.guard import (
    MARKER_LINE,
    analyze,
    annotate,
    is_unreviewed,
    verify,
    version_scripts,
)

HEADER = """\
from alembic import op
import sqlalchemy as sa

revision = 'abc123'
down_revision = None
"""


def write_migration(tmp_path: Path, upgrade: str, downgrade: str = "pass", marker: bool = True):
    """Build a migration file the way the template does, returning its path."""
    versions = tmp_path / "versions"
    versions.mkdir(exist_ok=True)
    body = HEADER
    if marker:
        body += f"\n{MARKER_LINE}\n"
    body += f"\n\ndef upgrade() -> None:\n    {upgrade}\n\n\ndef downgrade() -> None:\n    {downgrade}\n"
    path = versions / "abc123_test.py"
    path.write_text(body, encoding="utf-8")
    return path


def codes(path: Path) -> set[str]:
    return {f.code for f in analyze(path)}


# --- the marker ----------------------------------------------------------


def test_marker_blocks_until_deleted(tmp_path):
    path = write_migration(tmp_path, "pass")
    assert is_unreviewed(path)
    assert verify(tmp_path), "an unreviewed revision must block the upgrade"

    # Approval is exactly this: the line goes away.
    path.write_text(
        path.read_text(encoding="utf-8").replace(f"{MARKER_LINE}\n", ""), encoding="utf-8"
    )
    assert not is_unreviewed(path)
    assert verify(tmp_path) == []


def test_marker_is_parsed_not_grepped(tmp_path):
    """Mentioning the marker in prose must not count -- guard.py's own docstring
    contains the string, and a migration explaining why it was approved should
    be able to say the word without re-blocking itself."""
    path = write_migration(tmp_path, "pass", marker=False)
    path.write_text(
        f'"""Approved: the {MARKER_LINE} line was deleted."""\n'
        f"# see also: {MARKER_LINE}\n" + path.read_text(encoding="utf-8"),
        encoding="utf-8",
    )
    assert not is_unreviewed(path)


def test_marker_set_to_false_does_not_block(tmp_path):
    path = write_migration(tmp_path, "pass", marker=False)
    path.write_text(path.read_text(encoding="utf-8") + "\nUNREVIEWED = False\n", encoding="utf-8")
    assert not is_unreviewed(path)


# --- hazard analysis -----------------------------------------------------


@pytest.mark.parametrize(
    "statement,expected",
    [
        ("op.drop_table('posts')", "drop_table"),
        ("op.drop_column('posts', 'summary')", "drop_column"),
        ("op.alter_column('posts', 'kind', type_=sa.Text())", "type_change"),
        ("op.execute('DELETE FROM posts')", "raw_sql"),
        ("op.execute('TRUNCATE llm_calls')", "raw_sql"),
    ],
)
def test_destructive_operations_are_flagged(tmp_path, statement, expected):
    path = write_migration(tmp_path, statement)
    findings = analyze(path)
    assert expected in {f.code for f in findings}
    assert any(f.severe for f in findings)


@pytest.mark.parametrize(
    "statement",
    [
        "op.add_column('posts', sa.Column('x', sa.Text()))",
        "op.create_index('ix_x', 'posts', ['x'])",
        "op.alter_column('posts', 'old', new_column_name='new')",
        "op.execute('CREATE EXTENSION IF NOT EXISTS vector')",
        "op.alter_column('posts', 'kind', server_default=None)",
    ],
)
def test_safe_operations_are_not_flagged_severe(tmp_path, statement):
    """Crying wolf is a real failure mode: if routine migrations light up red,
    the DANGER lines stop being read."""
    path = write_migration(tmp_path, statement)
    assert not any(f.severe for f in analyze(path))


def test_rename_split_into_drop_and_add_is_called_out(tmp_path):
    """The exact shape autogenerate produces for a rename, and the exact reason
    this gate exists."""
    path = write_migration(
        tmp_path,
        "op.drop_column('posts', 'summary')\n"
        "    op.add_column('posts', sa.Column('abstract', sa.Text()))",
    )
    findings = analyze(path)
    assert "possible_rename" in {f.code for f in findings}
    assert any("data will be lost" in f.message for f in findings)


def test_drop_and_add_on_different_tables_is_not_a_rename(tmp_path):
    path = write_migration(
        tmp_path,
        "op.drop_column('posts', 'summary')\n"
        "    op.add_column('stories', sa.Column('abstract', sa.Text()))",
    )
    assert "possible_rename" not in codes(path)


def test_downgrade_is_not_analyzed(tmp_path):
    """Every migration's downgrade drops things; flagging them would fire on all
    of them and train the reader to skip the warnings."""
    path = write_migration(tmp_path, "pass", downgrade="op.drop_table('posts')")
    assert analyze(path) == []


def test_missing_upgrade_is_itself_a_finding(tmp_path):
    versions = tmp_path / "versions"
    versions.mkdir()
    path = versions / "abc123_test.py"
    path.write_text(HEADER, encoding="utf-8")
    assert "no_upgrade" in codes(path)


# --- annotation ----------------------------------------------------------


def test_hazards_are_written_above_the_marker(tmp_path):
    """The warning has to sit between the reader and the line they came to
    delete, or the deletion becomes a reflex."""
    path = write_migration(tmp_path, "op.drop_column('posts', 'summary')")
    annotate(path)
    lines = path.read_text(encoding="utf-8").splitlines()
    marker_at = lines.index(MARKER_LINE)
    warning_at = next(i for i, line in enumerate(lines) if "drops a column" in line)
    assert warning_at < marker_at
    assert is_unreviewed(path), "annotating must not approve anything"


def test_annotate_is_idempotent(tmp_path):
    path = write_migration(tmp_path, "op.drop_column('posts', 'summary')")
    annotate(path)
    once = path.read_text(encoding="utf-8")
    annotate(path)
    assert path.read_text(encoding="utf-8") == once


# --- the revisions actually shipped --------------------------------------


def test_shipped_revisions_are_reviewed():
    assert verify(MIGRATIONS_DIR) == [], "a revision in the repo still needs review"


def test_shipped_revisions_form_one_chain():
    """Two heads mean `upgrade head` is ambiguous and the stack fails to boot."""
    from alembic.script import ScriptDirectory

    config = alembic_config()
    config.attributes["skip_review_guard"] = True
    assert len(ScriptDirectory.from_config(config).get_heads()) == 1


def test_every_revision_is_importable_and_has_both_directions():
    for script in version_scripts(MIGRATIONS_DIR):
        source = script.read_text(encoding="utf-8")
        assert "def upgrade()" in source and "def downgrade()" in source, script.name
