"""Migration workflow CLI — `python -m episteme.migrations <command>`.

    status            what exists, what is unreviewed, what the database is on
    new -m "..."      autogenerate a draft revision from model changes
    check <rev>       re-run the hazard analysis on one revision
    upgrade           apply everything pending (refuses anything unreviewed)
    history           the revision graph

Approving a migration is not a command: it is deleting the `UNREVIEWED = True`
line from the script by hand, after reading it. `new` writes the hazards it
found into comments directly above that line so the deletion cannot be a
reflex. See guard.py for why autogenerated migrations need this at all.
"""

from __future__ import annotations

import argparse
import asyncio
import sys
from pathlib import Path

from alembic import command
from alembic.script import ScriptDirectory

from episteme.migrations import MIGRATIONS_DIR, VERSIONS_DIR, alembic_config
from episteme.migrations.guard import (
    MARKER_LINE,
    analyze,
    annotate,
    is_unreviewed,
    verify,
    version_scripts,
)


def _resolve(revision: str) -> Path:
    """Accept a revision id, a full filename, or an unambiguous prefix."""
    candidates = [
        p
        for p in version_scripts(MIGRATIONS_DIR)
        if p.stem == revision or p.name == revision or p.stem.startswith(f"{revision}_")
    ]
    if not candidates:
        sys.exit(
            f"No revision matching {revision!r} in {VERSIONS_DIR}.\n"
            "Run `python -m episteme.migrations status` to list them."
        )
    if len(candidates) > 1:
        sys.exit(f"{revision!r} is ambiguous: {', '.join(p.stem for p in candidates)}")
    return candidates[0]


async def _database_revision() -> str | None:
    """Revision recorded in the database, or None if unreachable or absent."""
    from sqlalchemy import text

    from episteme.db import engine

    try:
        async with engine.connect() as conn:
            if not (await conn.execute(text("SELECT to_regclass('alembic_version')"))).scalar_one():
                return None
            row = (await conn.execute(text("SELECT version_num FROM alembic_version"))).first()
            return row[0] if row else None
    except Exception:
        return None
    finally:
        await engine.dispose()


def cmd_status(_args) -> int:
    scripts = version_scripts(MIGRATIONS_DIR)
    current = asyncio.run(_database_revision())

    print(f"\nRevisions in {VERSIONS_DIR}:\n")
    if not scripts:
        print("  (none yet)")
    for script in scripts:
        state = "UNREVIEWED" if is_unreviewed(script) else "reviewed"
        here = "  <- database is here" if current and script.stem.startswith(current) else ""
        print(f"  {script.stem:<46} {state}{here}")
        if is_unreviewed(script):
            for finding in analyze(script):
                print(finding.render())

    print(f"\nDatabase revision: {current or 'none (no alembic_version table)'}")
    if problems := verify(MIGRATIONS_DIR):
        print(f"\n{len(problems)} revision(s) blocking `upgrade`:\n")
        for problem in problems:
            print(f"  * {problem}")
        print()
        return 1
    print("\nAll revisions reviewed; `upgrade` is clear to run.\n")
    return 0


def cmd_new(args) -> int:
    if problems := verify(MIGRATIONS_DIR):
        print("Warning: existing revisions still need review:\n")
        for problem in problems:
            print(f"  * {problem}")
        print("\nReview them before generating more, or the drafts will stack up.\n")

    config = alembic_config()
    # Generating a revision writes a file and applies nothing, so the gate that
    # protects the database does not apply to it.
    config.attributes["skip_review_guard"] = True

    before = set(version_scripts(MIGRATIONS_DIR))
    command.revision(config, message=args.message, autogenerate=not args.empty)
    written = sorted(set(version_scripts(MIGRATIONS_DIR)) - before)

    for script in written:
        findings = annotate(script)
        print(f"\nDraft: {script}")
        for finding in findings:
            print(finding.render())
        if any(f.severe for f in findings):
            print(
                "\n  ^ This draft can DESTROY DATA. If a drop+add pair is really a\n"
                "    rename, replace it with op.alter_column(new_column_name=...)."
            )
    print(
        f"\nRead it, correct it, then delete its `{MARKER_LINE}` line to approve.\n"
        "Nothing is applied until you do.\n"
    )
    return 0


def cmd_check(args) -> int:
    script = _resolve(args.revision)
    findings = analyze(script)
    print(f"\n{script.name}: {'UNREVIEWED' if is_unreviewed(script) else 'reviewed'}\n")
    if not findings:
        print("  No destructive operations detected.\n")
        return 0
    for finding in findings:
        print(finding.render())
    print()
    return 0


def cmd_upgrade(args) -> int:
    command.upgrade(alembic_config(), args.target)  # gated in env.py
    print(f"\nDatabase upgraded to {args.target}.\n")
    return 0


def cmd_history(_args) -> int:
    config = alembic_config()
    config.attributes["skip_review_guard"] = True
    for revision in ScriptDirectory.from_config(config).walk_revisions():
        print(f"  {revision.revision:<16} {revision.doc.splitlines()[0]}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python -m episteme.migrations", description=__doc__.split("\n\n")[0]
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    subparsers.add_parser("status", help="what exists, what is unreviewed").set_defaults(
        fn=cmd_status
    )

    new = subparsers.add_parser("new", help="autogenerate a draft revision")
    new.add_argument("-m", "--message", required=True)
    new.add_argument(
        "--empty",
        action="store_true",
        help="skip autogenerate and scaffold an empty revision (for data migrations "
        "and anything a schema diff cannot see)",
    )
    new.set_defaults(fn=cmd_new)

    check = subparsers.add_parser("check", help="hazard analysis for one revision")
    check.add_argument("revision")
    check.set_defaults(fn=cmd_check)

    upgrade = subparsers.add_parser("upgrade", help="apply pending revisions")
    upgrade.add_argument("target", nargs="?", default="head")
    upgrade.set_defaults(fn=cmd_upgrade)

    subparsers.add_parser("history", help="the revision graph").set_defaults(fn=cmd_history)

    args = parser.parse_args(argv)
    return args.fn(args)


if __name__ == "__main__":
    raise SystemExit(main())
