"""Alembic environment.

Three things here are load-bearing and easy to get wrong:

1. **The review gate runs from here**, not from a wrapper script, because this
   module executes on *every* path into alembic — our CLI, `bootstrap`, and a
   bare `alembic upgrade head` typed into a shell all land here. It fails
   closed: a programmatic invocation whose command name cannot be determined is
   treated as "about to apply migrations" and is gated.
2. **Procrastinate's tables are excluded from autogenerate.** They are created
   by procrastinate's own schema tool, so they exist in the database but not in
   `Base.metadata` — without this filter every autogenerated migration would
   open with `op.drop_table('procrastinate_jobs')` and take the job queue with
   it.
3. **pgvector columns render as `Vector(dim)`** with the matching import, so
   generated scripts are valid Python instead of referring to a `sa.VECTOR`
   that does not exist.
"""

from __future__ import annotations

import asyncio

from alembic import context
from pgvector.sqlalchemy import Vector
from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

from episteme import models
from episteme.config import settings
from episteme.migrations import MIGRATIONS_DIR
from episteme.migrations.guard import verify

config = context.config
target_metadata = models.Base.metadata

# Owned by procrastinate's own schema management (bootstrap applies it); invisible
# to Base.metadata and therefore must never appear in a schema diff.
FOREIGN_TABLE_PREFIX = "procrastinate_"

# Commands that write schema changes. Anything not in this set — `revision`,
# `current`, `history`, `stamp` — inspects or records without applying DDL from a
# script, so it is not gated.
APPLYING_COMMANDS = {"upgrade", "downgrade"}


def _guard_should_run() -> bool:
    if config.attributes.get("skip_review_guard"):
        # Set only by bootstrap's one-time adoption of a pre-Alembic database,
        # which stamps a version row and applies no DDL.
        return False
    cmd = getattr(getattr(config, "cmd_opts", None), "cmd", None)
    if not cmd:
        return True  # programmatic call: assume it applies, and gate it
    return getattr(cmd[0], "__name__", "") in APPLYING_COMMANDS


def enforce_review_gate() -> None:
    problems = verify(MIGRATIONS_DIR)
    if not problems:
        return
    raise SystemExit(
        "\n".join(
            [
                "",
                "=" * 78,
                "MIGRATION BLOCKED -- unreviewed schema changes",
                "=" * 78,
                "",
                *(f"  * {p}" for p in problems),
                "",
                "Autogenerated migrations are drafts: a rename looks identical to",
                "'drop column, add column', and applying that draft destroys the",
                "column's data. Nothing is applied until the script has been read,",
                "corrected, and its UNREVIEWED marker deleted by hand.",
                "",
                "  python -m episteme.migrations status         # what needs review",
                "  python -m episteme.migrations check <rev>    # what it does to data",
                "",
            ]
        )
    )


def include_object(obj, name, type_, reflected, compare_to) -> bool:
    if type_ == "table" and (name or "").startswith(FOREIGN_TABLE_PREFIX):
        return False
    if type_ == "index":
        table_name = getattr(getattr(obj, "table", None), "name", "") or ""
        if table_name.startswith(FOREIGN_TABLE_PREFIX):
            return False
    return True


def render_item(type_, obj, autogen_context) -> str | bool:
    """Emit `Vector(1024)` (plus its import) instead of alembic's default
    rendering, which does not round-trip pgvector types."""
    if type_ == "type" and isinstance(obj, Vector):
        autogen_context.imports.add("from pgvector.sqlalchemy import Vector")
        return f"Vector({obj.dim})"
    return False


def _configure(**kwargs) -> None:
    context.configure(
        target_metadata=target_metadata,
        include_object=include_object,
        render_item=render_item,
        compare_type=True,
        compare_server_default=True,
        # Alembic's default renderer knows sqlalchemy; anything else (Vector)
        # needs the import declared, which render_item does.
        render_as_batch=False,
        **kwargs,
    )


def run_migrations_offline() -> None:
    """Emit SQL to stdout (`--sql`) without a database connection."""
    if _guard_should_run():
        enforce_review_gate()
    _configure(url=settings.sqlalchemy_url, literal_binds=True, dialect_opts={"paramstyle": "named"})
    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    _configure(connection=connection)
    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    engine = async_engine_from_config(
        {"sqlalchemy.url": settings.sqlalchemy_url},
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    async with engine.connect() as connection:
        await connection.run_sync(do_run_migrations)
    await engine.dispose()


def run_migrations_online() -> None:
    if _guard_should_run():
        enforce_review_gate()
    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
